breedx2/cuspid

static/anim.js, static/cuspid.js
Fixed 4 tickets on breedx2/cuspid. (See commit messages for details.)
=> Bug fixes and new key assignments

static/anim-boxscroll.js
=> Prevent moving image off camera, either by scrolling or by zooming

static/anim-twoquadboxscroll.js, static/cuspid.js, static/key_handler.js
Fix key bug on negative delta x.
This addresses #17
=> Support for multiple images in box scroll. 

static/anim-twoquadboxscroll.js, static/cuspid.js, static/key_handler.js
This addresses #33 
There's still plenty of work to be done related to actual image/quad management...but hopefully this is a step forward.
=> Let n key cycle thru all loaded images

src/anim-twoquadboxscroll.js, src/key_handler.js
=> fix reversing bug to make moar smoother

src/anim-twoquadboxscroll.js
Resolves #24 
Still not _super_ stoked on where the zoom point of focus is, but that's another issue maybe.
=> dont clamp, just ensure other quads way off viewport

src/cuspid.js, src/image-loader.js, src/video-loader.js
=> Add html5 support via video texture

src/anim-image-sequence.js, src/cuspid.js, src/key_handler.js, views/keys.jade
=> Image sequence

src/Animator.js, src/cuspid.js, src/effect_composer.js, src/key_handler.js, views/keys.jade, webpack.config.js
This addresses #16 
...and it looks pretty sweet.
=> Dot shader

package.json, src/Animator.js, src/anim-palette.js, src/key_handler.js, webpack.common.js, webpack.dev.js, webpack.prod.js
=> Reset palette

src/anim-palette.js, src/anim-twoquadboxscroll.js, src/clamp_pos.js, src/zoom_nudge.js
=> Palette zoom

src/anim-image-sequence.js
=> Sequence zoom

src/cuspid_shader.js
(untested) This may fix the GLSL issue where white pixels are displayed as black.
=> Possible fix for #56: White areas are displayed as black

src/Animator.js, src/anim-image-sequence.js, src/anim-palette.js, src/anim-zoomer.js, src/event_actions.js
This changes how next is handled (pushed into each animation) and should address #65
=> Fix next image

README.md, src/anim-zoomer-seq.js, src/cuspid.js, src/event_actions.js, src/key_handler.js, src/ws-events.js, views/keys.pug
First part of addressing #39.  This only goes one direction, so will add the other direction support in a following PR.
=> Zoomer sequence

README.md, src/anim-zoomer-seq.js, src/cuspid.js, src/event_actions.js, src/key_handler.js, src/ws-events.js, views/keys.pug
zoom sequence now respects direction and this should close out #39
=> add zoom sequence in the other direction too (out)

src/anim-zoomer.js, src/cuspid.js, src/event_actions.js
This resolves #25.
After learning a few things from building the tunnel zoomer, it seemed like a good time to rework some of the previous zoomer and fix #25.
=> Rework zoom

src/cuspid.js
Fixes #83.
We were using the wrong kind of texture.
=> fix broken video playback

deploy/README.md, deploy/deploy.sh
=> add simple deploy infoz

pd/controller.pd
=> add tunnel seq and clean up

README.md, src/Animator.js, src/event_actions.js, src/key_handler.js, src/ws-events.js, views/keys.pug
=> add ability to advance one fake frame

README.md, pd/controller.pd, src/Animator.js, src/cuspid.js, src/effect_composer.js, src/event_actions.js, src/invert_shader.js, src/key_handler.js, src/ws-events.js, views/keys.pug
Resolves #100. 
Decided to do this as an effect (instead of a mode), because it's best done with a `ShaderPass` that uses an inverting shader.  I was using the wrong lingo when I filed the issue originally.
I think there's room to automate/control the speed with which inversion is applied, but in the interest of progress I'm going to close this out and create a separate issue.
=> add invert effect

package-lock.json, package.json, webpack.prod.js
=> Uglify to terser

src/Animator.js, src/event-actions.js
=> re-use effect composer when changing animations

src/anim-blend.js
=> add zoom and nudge ability to blend mode

src/anim-blend.js, src/anim-image-sequence.js, src/anim-palette.js, src/zoom-nudge.js
Just uses monkeypatching to reduce some duplicated code / boilerplate.
=> Smarter zoom nudge binding

src/Animator.js, src/anim-blend.js, src/cuspid-shader.js
=> default to normal blend, set up once in blend animation (cant do it in constructor)

pd/controller.pd, src/ws-events.js
=> add blend to osc and pd

deploy/deploy.sh, package.json
Fixes #106 and cuts the size of `budle.js` by more than half.
=> use prod webpack

README.md, pd/controller.pd, src/event-actions.js, src/key-handler.js, src/ws-events.js, views/keys.pug
Resolves #81 by adding a still image mode.  It's the image sequence mode, but with time set to infinity.
=> add still image mode

README.md, pd/controller.pd, src/event-actions.js, src/ws-events.js
=> add imageSet selection via osc/ws/pd

src/image-loader.js, src/video-loader.js
resolves #132 and also removes broken cache for video loader.
=> remove broken cache

src/ui/imagepool-ui.js, src/ui/preview.js, static/cuspid.css, views/imagepool.pug
=> populate tab 1 & 2 with default sets

README.md, docs/KEYS.md
=> pull out keys to own doc
